name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Download ngrok
      run: curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth ngrok
      run: ./ngrok/ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install XQuartz and XRDP
      run: |
        brew install xquartz
        brew install xrdp
    - name: Start XQuartz
      run: open -a XQuartz
    - name: Configure XRDP
      run: |
        sudo /etc/xrdp/xrdp.ini
        sudo /etc/xrdp/startwm.sh
    - name: Enable Remote Management
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users runneradmin -privs -all -restart -agent -menu
    - name: Set User & Password
      run: |
        sudo dscl . -create /Users/runneradmin
        sudo dscl . -create /Users/runneradmin UserShell /bin/bash
        sudo dscl . -create /Users/runneradmin RealName "CI Runner Admin"
        sudo dscl . -passwd /Users/runneradmin P@ssw0rd!
        sudo dscl . -create /Users/runneradmin UniqueID "1010"
        sudo dscl . -create /Users/runneradmin PrimaryGroupID 80
        sudo dscl . -create /Users/runneradmin NFSHomeDirectory /Users/runneradmin
        sudo createhomedir -c -u runneradmin
    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 3389
