name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Download
      run: curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable Remote Login
      run: sudo systemsetup -setremotelogin on
    - name: Check User
      run: |
        if ! id "runneradmin" &>/dev/null; then
          sudo dscl . -create /Users/runneradmin
          sudo dscl . -create /Users/runneradmin UserShell /bin/bash
          sudo dscl . -create /Users/runneradmin RealName "Runner Admin"
          sudo dscl . -create /Users/runneradmin UniqueID "1010"
          sudo dscl . -create /Users/runneradmin PrimaryGroupID 80
          sudo dscl . -create /Users/runneradmin NFSHomeDirectory /Users/runneradmin
          sudo dscl . -passwd /Users/runneradmin P@ssw0rd!
          sudo createhomedir -c -u runneradmin > /dev/null
        fi
    - name: Create Tunnel
      run: ./ngrok tcp 3389
