name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install dependencies
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
        brew install autoconf automake libtool pkg-config
        brew install openssl
        brew install libx11 libxfixes libxrandr libxrender nasm
    - name: Clone xrdp repository
      run: |
        git clone https://github.com/neutrinolabs/xrdp.git
        cd xrdp
        ./bootstrap
        ./configure --prefix=/usr/local --exec-prefix=/usr/local --sysconfdir=/etc --localstatedir=/var --enable-fuse --enable-jpeg --enable-painter --enable-vsock --enable-pixman --enable-rdpdr --enable-mp3lame --enable-pulseaudio --enable-mp3lame
        make
        sudo make install
    - name: Start xrdp
      run: |
        sudo xrdp-sesman
        sudo xrdp
    - name: Download ngrok
      run: curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Create Tunnel
      run: ./ngrok tcp 3389
