name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker build -t your-docker-image-name .
        echo $KOYEB_API_KEY | docker login -u _ --password-stdin registry.koyeb.com
        docker tag your-docker-image-name registry.koyeb.com/your-koyeb-app-name/your-docker-image-name
        docker push registry.koyeb.com/your-koyeb-app-name/your-docker-image-name
      env:
        KOYEB_API_KEY: r68hrua7pduys3op6ztkjdot37q64g46ubkp0ja8k5xvbi5we0zbv7nusf16lue3

    - name: Deploy to Koyeb
      run: |
        curl -X POST https://api.koyeb.com/v1/services/your-koyeb-app-name/deployments \
        -H "Authorization: Bearer $KOYEB_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{"docker_image": "registry.koyeb.com/your-koyeb-app-name/your-docker-image-name"}'
