name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup xRDP
      run: |
        sudo apt update && sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo adduser xrdp ssl-cert
        sudo systemctl restart xrdp

    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Tunnel
      run: ./ngrok tcp 3389
