name: Android CI

on: [push, workflow_dispatch]

jobs:
  setup-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d android-sdk
        echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/android-sdk/cmdline-tools/bin" >> $GITHUB_PATH
        echo "$GITHUB_WORKSPACE/android-sdk/platform-tools" >> $GITHUB_PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Install Android Emulator
      run: |
        sdkmanager "emulator" "system-images;android-30;google_apis;x86_64"
        echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"
        $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-audio -no-window &

    - name: Setup RDP
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ubuntu-desktop
        sudo apt-get install -y --no-install-recommends xrdp
        sudo adduser xrdp ssl-cert
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        echo "runneradmin:P@ssw0rd!" | sudo chpasswd
        sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config

    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok tunnel
      run: ./ngrok tcp 3389 --region=us --authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
