name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup RDP
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ubuntu-desktop
        sudo apt-get install -y --no-install-recommends xrdp
        sudo adduser xrdp ssl-cert
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        echo "runneradmin:P@ssw0rd!" | sudo chpasswd
        sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Start ngrok tunnel
      run: ./ngrok tcp 3389 --region=us --authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
