name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Download
      run: curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable Remote Login
      run: sudo systemsetup -setremotelogin on
    - name: Set Password
      run: sudo dscl . -passwd /Users/runneradmin P@ssw0rd!
    - name: Create Tunnel
      run: ./ngrok tcp 3389
